#! /usr/bin/Rscript --vanilla
#============================================
suppressPackageStartupMessages(library("optparse"))
#====================================================================
option_list <- list(
  make_option(c("-f", "--files"), type="character", default="genes.fpkm_tracking",
              help="To specify fpkm files generated by cufflinks with comma-separate [default %default]"),
  make_option(c("-l", "--labels"), type="character", default="",
              help="To specify labels [default %default]"),
  make_option(c("-o", "--output"), type="character", default="Expression_TPM",
              help="To specify output file [default %default]"))

parser <- OptionParser(usage = "%prog [options]", option_list=option_list,
                       description = "\nThe script is to convert FPKMs into TPMs.",
                       epilogue="Feizhen Wu(wufz@fudan.edu.cn), July 09, 2018.\n"
)
arguments <- parse_args(parser, positional_arguments =0,print_help_and_exit=T)
opt <- arguments$options
files=strsplit(opt$files,",")[[1]]
labels=strsplit(opt$labels,",")[[1]]
output=opt$output

#files=c("M_KO1_bear_1wk.fpkm","M_KO2_bear_1wk.fpkm","M_KO3_bear_1wk.fpkm","M_WT1_bear_1wk.fpkm","M_WT2_bear_1wk.fpkm","M_WT3_bear_1wk.fpkm")
#labels=c("M_KO1_bear_1wk","M_KO2_bear_1wk","M_KO3_bear_1wk","M_WT1_bear_1wk","M_WT2_bear_1wk","M_WT3_bear_1wk")

library(data.table)
library(pheatmap)
TPM=function(myfile,myName=myfile){
  if(myName==myfile){
    myName=sub(pattern = "(.*)\\..*$", replacement = "\\1", basename(myfile))
  }
  cat("The label of",myfile," was assigned as ",myName,"!\n")
  if( file.access(myfile) == -1) {
    stop(sprintf("Specified file ( %s ) does not exist", myfile))
  }
  Exp=fread(myfile,header=T)[,c("gene_id","FPKM")]
  Exp=Exp[!grep("^Mir",Exp$gene_id),]
  Exp=Exp[!grep("^MIR",Exp$gene_id),]
  Exp=Exp[!duplicated(Exp$gene_id),]
  ss=sum(Exp$FPKM)
  Exp$Tpm=Exp$FPKM/ss*10^6
  names(Exp)[3]=myName
  Exp=Exp[,-2]
  return(Exp)
}

#===================================
if(length(labels)>0){
  Exp=TPM(files[1],labels[1])  
}else{
  Exp=TPM(files[1])
}

Exp=Exp[!duplicated(Exp$gene_id),]
i=2
while(i<=length(files)){
  if(i<=length(labels)){
    Exp1=TPM(files[i],labels[i])
  }else{
    Exp1=TPM(files[i])
  }
  Exp1=Exp1[!duplicated(Exp1$gene_id),]
  Exp=merge(Exp,Exp1,by="gene_id")
  Exp=Exp[!duplicated(Exp$gene_id),]
  i=i+1
}

fwrite(Exp,file = paste(output,".xls",sep=""),quote = F,sep="\t",row.names=F)

Exp=Exp[,-1]
p=cor(Exp)

write.table(p,file = paste(output,"_correlation.txt",sep=""),quote = F,sep="\t",row.names=T)

pdf(file = paste(output,"_correlation.pdf",sep=""),height = 400/100,width = 500/100,onefile = F)
pheatmap(p,fontsize = 8)
dev.off()
